"use client";
import { ThreeDMarquee } from "@/components/ui/shadcn-io/3d-marquee";
export default function ThreeDMarqueeDemo() {
  const images = [
    // "https://storage.googleapis.com/gweb-uniblog-publish-prod/original_images/tenor_1.gif",
    // "https://storage.googleapis.com/gweb-uniblog-publish-prod/original_images/tenor_1.gif",
    // "https://media.giphy.com/media/ICOgUNjpvO0PC/giphy.gif",
    // "https://media.giphy.com/media/l0HlQ7LRal7hRTd8w/giphy.gif",
    // "https://media.giphy.com/media/3o6Zt481isNVuQI1l6/giphy.gif",
    // "https://media.giphy.com/media/xT0xeJpnrWC4XWblEk/giphy.gif",
    // "https://media.giphy.com/media/26tPoyDhjiJ2g7rEs/giphy.gif",
    // "https://media.giphy.com/media/3oriO0OEd9QIDdllqo/giphy.gif",
    // "https://media.giphy.com/media/ICOgUNjpvO0PC/giphy.gif",
    // "https://media.giphy.com/media/xT0xeJpnrWC4XWblEk/giphy.gif",
    // "https://media.giphy.com/media/26tPoyDhjiJ2g7rEs/giphy.gif",
    // "https://media.giphy.com/media/3oriO0OEd9QIDdllqo/giphy.gif",
    // "https://media.giphy.com/media/ICOgUNjpvO0PC/giphy.gif",
    // "https://media.giphy.com/media/xT0xeJpnrWC4XWblEk/giphy.gif",
    // "https://media.giphy.com/media/26tPoyDhjiJ2g7rEs/giphy.gif",
    // "https://media.giphy.com/media/3oriO0OEd9QIDdllqo/giphy.gif",
    // "https://storage.googleapis.com/gweb-uniblog-publish-prod/original_images/tenor_1.gif",
    // "https://storage.googleapis.com/gweb-uniblog-publish-prod/original_images/tenor_1.gif",
    "https://media.giphy.com/media/ICOgUNjpvO0PC/giphy.gif",
    "https://storage.googleapis.com/theblucksshortform/public%20assets/marquee/video_01.mp4",
    "https://storage.googleapis.com/theblucksshortform/public%20assets/marquee/video_02.mp4",
    "https://storage.googleapis.com/theblucksshortform/public%20assets/marquee/image.png",
    "https://storage.googleapis.com/theblucksshortform/public%20assets/marquee/image2.png",
    "https://storage.googleapis.com/theblucksshortform/public%20assets/marquee/video_01.mp4",
    "https://media.giphy.com/media/3oriO0OEd9QIDdllqo/giphy.gif",
    "https://storage.googleapis.com/theblucksshortform/public%20assets/marquee/video_03.mp4",
    "https://storage.googleapis.com/theblucksshortform/public%20assets/marquee/image3.png",
    "https://storage.googleapis.com/theblucksshortform/public%20assets/marquee/image4.png",
    "https://storage.googleapis.com/theblucksshortform/public%20assets/marquee/video_02.mp4",
    "https://storage.googleapis.com/theblucksshortform/public%20assets/marquee/image5.png",

    // "https://assets.aceternity.com/animated-modal.png",
    // "https://assets.aceternity.com/animated-testimonials.webp",
    // "https://assets.aceternity.com/cloudinary_bkp/Tooltip_luwy44.png",
    // "https://assets.aceternity.com/github-globe.png",
    // "https://assets.aceternity.com/glare-card.png",
    // "https://assets.aceternity.com/layout-grid.png",
    // "https://assets.aceternity.com/flip-text.png",
    // "https://assets.aceternity.com/hero-highlight.png",
    // "https://assets.aceternity.com/carousel.webp",
    // "https://assets.aceternity.com/placeholders-and-vanish-input.png",
    // "https://assets.aceternity.com/shooting-stars-and-stars-background.png",
    // "https://assets.aceternity.com/signup-form.png",
    // "https://assets.aceternity.com/cloudinary_bkp/stars_sxle3d.png",
    // "https://assets.aceternity.com/spotlight-new.webp",
    // "https://assets.aceternity.com/cloudinary_bkp/Spotlight_ar5jpr.png",
    // "https://assets.aceternity.com/cloudinary_bkp/Parallax_Scroll_pzlatw_anfkh7.png",
    // "https://assets.aceternity.com/tabs.png",
    // "https://assets.aceternity.com/cloudinary_bkp/Tracing_Beam_npujte.png",
    // "https://assets.aceternity.com/cloudinary_bkp/typewriter-effect.png",
    // "https://assets.aceternity.com/glowing-effect.webp",
    // "https://assets.aceternity.com/hover-border-gradient.png",
    // "https://assets.aceternity.com/cloudinary_bkp/Infinite_Moving_Cards_evhzur.png",
    // "https://assets.aceternity.com/cloudinary_bkp/Lamp_hlq3ln.png",
    // "https://assets.aceternity.com/macbook-scroll.png",
    // "https://assets.aceternity.com/cloudinary_bkp/Meteors_fye3ys.png",
    // "https://assets.aceternity.com/cloudinary_bkp/Moving_Border_yn78lv.png",
    // "https://assets.aceternity.com/multi-step-loader.png",
    // "https://assets.aceternity.com/vortex.png",
    // "https://assets.aceternity.com/wobble-card.png",
    // "https://assets.aceternity.com/world-map.webp",
  ];
  return (
    <div className="mx-auto max-w-7xl max-h-screen overflow-hidden rounded-3xl p-5">
      <ThreeDMarquee images={images} />
    </div>
  );
}
